/* Les noms, textes et profils ci-dessous se modifient facilement. */
window.QUIZ_SERVICES = [
 {id:'accueil-etat-civil',name:'Accueil – État civil – Citoyenneté',shortName:'Accueil & citoyenneté',profile:{public:5,cadre:3,soutien:3,analyse:1},description:'Tu sais accueillir les demandes avec calme, même quand elles arrivent toutes en même temps et qu’un parapheur a décidé de prendre sa pause. Tu rends les démarches plus simples et chaque personne se sent attendue.',catchphrase:'« Bonjour, on va regarder ça ensemble. »',certificateText:'Pour son sens de l’accueil, sa précision et sa capacité à rendre chaque démarche plus humaine.'},
 {id:'secretariat-general',name:'Secrétariat général',shortName:'Secrétariat général',profile:{cadre:5,analyse:4,soutien:2,animation:2},description:'Tu repères le fil rouge d’un dossier au milieu de douze pièces jointes et d’un ordre du jour ambitieux. Ta maîtrise de la coordination donne à l’action collective une belle colonne vertébrale.',catchphrase:'« Pour que tout le monde avance dans le même sens, commençons par le début. »',certificateText:'En reconnaissance de sa vision d’ensemble, de son sens de l’organisation et de son art du lien.'},
 {id:'police-municipale',name:'Police municipale',shortName:'Police municipale',profile:{urgence:5,terrain:4,cadre:4,public:3},description:'Tu gardes la tête froide, le sens du dialogue et le regard attentif aux réalités du terrain. Dans l’imprévu, tu sais conjuguer présence, discernement et respect du cadre.',catchphrase:'« La bonne réponse commence souvent par une bonne écoute. »',certificateText:'Pour son discernement, sa disponibilité et son engagement au service d’un cadre de vie serein.'},
 {id:'services-techniques',name:'Services techniques',shortName:'Services techniques',profile:{terrain:5,urgence:3,analyse:2,idee:2},description:'Quand quelque chose fonctionne, tu as souvent contribué à le rendre possible. Quand un imprévu surgit, tu imagines déjà une solution concrète, durable et adaptée au terrain.',catchphrase:'« On va trouver une solution qui tient debout. »',certificateText:'En raison de son esprit pratique, de sa maîtrise technique et de son sens du service rendu.'},
 {id:'astreinte-technique',name:'Astreinte technique',shortName:'Astreinte technique',profile:{urgence:5,terrain:5,analyse:2},description:'Tu sais qu’un imprévu n’a pas toujours la délicatesse d’attendre lundi matin. Réactif et méthodique, tu sais prioriser, sécuriser et mobiliser les bonnes ressources.',catchphrase:'« Reçu. On évalue, on sécurise, on agit. »',certificateText:'Pour sa disponibilité, son sang-froid et sa capacité à remettre la situation sur de bons rails.'},
 {id:'environnement',name:'Environnement',shortName:'Environnement',profile:{vivant:5,terrain:3,cadre:2,idee:2},description:'Tu regardes le paysage avec curiosité et tu penses aux équilibres qui le font vivre. Entre observation patiente et action concrète, tu aides le territoire à grandir avec attention.',catchphrase:'« Le vivant a parfois son propre calendrier, et il mérite qu’on l’écoute. »',certificateText:'En reconnaissance de son attention au vivant et de son engagement pour un territoire durable.'},
 {id:'mouillages-affaires-maritimes',name:'Mouillages – Affaires maritimes',shortName:'Mouillages & affaires maritimes',profile:{vivant:4,terrain:4,cadre:4,public:2},description:'Tu sais que le littoral est un espace vivant, partagé et précieux. Ton sens de l’organisation garde le cap entre réglementation, usagers et humeur changeante de la mer.',catchphrase:'« On garde le cap, même quand la marée change le programme. »',certificateText:'Pour sa connaissance du littoral, son sens du dialogue et sa vigilance maritime.'},
 {id:'urbanisme-vie-economique',name:'Urbanisme – Vie économique',shortName:'Urbanisme & économie',profile:{cadre:4,analyse:4,idee:3,terrain:2},description:'Tu sais relier une idée, un lieu, des règles et des personnes. Ta vision se construit dans la durée, avec assez de pragmatisme pour transformer les plans en projets vivants.',catchphrase:'« Un bon projet commence par une bonne lecture du lieu. »',certificateText:'En raison de sa vision à long terme, de sa rigueur et de sa capacité à faire dialoguer les projets.'},
 {id:'ccas',name:'Centre communal d’action sociale',shortName:'Action sociale',profile:{soutien:5,public:5,cadre:2},description:'Tu sais écouter au-delà de la première phrase et chercher la réponse la plus utile à une situation singulière. La solidarité, pour toi, se construit avec tact et avec les personnes.',catchphrase:'« Chaque situation mérite une réponse attentive. »',certificateText:'Pour son écoute, son discernement et son engagement concret en faveur des habitants.'},
 {id:'maison-habitants',name:'Maison des habitants – Centre social de Séné',shortName:'Maison des habitants',profile:{animation:5,public:4,soutien:3,idee:3},description:'Tu aimes faire place aux idées, aux rencontres et aux initiatives. Tu sais qu’un lieu prend vie quand chacun peut y apporter quelque chose et se sentir à sa place.',catchphrase:'« La meilleure activité, c’est souvent celle qu’on construit ensemble. »',certificateText:'En reconnaissance de son énergie collective, de sa créativité et de son sens de l’animation.'},
 {id:'residence-penhoet',name:'Résidence autonomie de Penhoët',shortName:'Résidence de Penhoët',profile:{soutien:5,public:4,animation:2,cadre:2},description:'Tu prêtes attention aux habitudes, aux envies et aux petits détails qui rendent le quotidien plus agréable. Tu cultives un accompagnement chaleureux où l’autonomie garde toute sa place.',catchphrase:'« Le quotidien mérite autant d’attention que les grands jours. »',certificateText:'Pour son attention bienveillante, son sens du lien et son respect de l’autonomie de chacun.'},
 {id:'finances-comptabilite',name:'Finances – Comptabilité',shortName:'Finances & comptabilité',profile:{analyse:5,cadre:5},description:'Tu sais que derrière chaque chiffre se trouve une décision utile au collectif. Tu avances avec précision, méthode et le calme admirable de qui sait où se trouve la bonne version du fichier.',catchphrase:'« Les chiffres racontent une histoire ; vérifions les virgules. »',certificateText:'En raison de sa précision, de sa fiabilité et de son attention à la bonne gestion collective.'},
 {id:'marches-juridiques',name:'Marchés publics et affaires juridiques',shortName:'Marchés & affaires juridiques',profile:{cadre:5,analyse:4,public:2},description:'Tu apprécies les décisions solides, les règles bien comprises et les dossiers qui arrivent complets. Ta vigilance rend les projets plus sûrs et la commande publique plus lisible.',catchphrase:'« Lisons la petite ligne : elle a souvent une grande idée. »',certificateText:'Pour sa rigueur, son sens de l’équité et sa contribution à des décisions bien sécurisées.'},
 {id:'drh',name:'Direction des ressources humaines',shortName:'Ressources humaines',profile:{soutien:4,cadre:4,public:3,analyse:3},description:'Tu vois à la fois les parcours, les besoins et les conditions qui permettent à chacun de contribuer. Tu sais associer écoute, cadre clair et vision d’équipe.',catchphrase:'« Une organisation avance quand les personnes peuvent y trouver leur place. »',certificateText:'En reconnaissance de son écoute, de son sens de l’équité et de son attention au collectif de travail.'},
 {id:'petite-enfance-jeunesse',name:'Petite enfance, enfance, jeunesse et vie scolaire',shortName:'Enfance & jeunesse',profile:{animation:5,soutien:4,public:3,idee:2},description:'Tu sais qu’une journée réussie se prépare avec sérieux et garde aussi une place pour l’imprévu, le jeu et les découvertes. Tu accompagnes les jeunes avec attention et imagination.',catchphrase:'« On avait prévu un plan. Les enfants ont eu une meilleure idée. »',certificateText:'Pour son énergie éducative, son imagination et son engagement auprès des jeunes générations.'},
 {id:'sport-culture-associatif',name:'Sport, culture et vie associative',shortName:'Sport, culture & associations',profile:{animation:5,idee:4,terrain:3,public:2},description:'Tu sais qu’un événement, une pratique ou une association peut faire naître des liens durables. Ton énergie transforme les idées en rendez-vous où la commune se retrouve.',catchphrase:'« À vos marques, prêts… et qui a la clé de la salle ? »',certificateText:'En raison de son enthousiasme, de son sens de l’organisation et de son soutien à la vie locale.'},
 {id:'communication',name:'Communication',shortName:'Communication',profile:{idee:5,public:3,animation:3,analyse:1},description:'Tu repères l’angle, le ton et l’image qui feront passer une information clairement. Tu sais raconter le quotidien municipal sans oublier que les habitants n’ont pas tous lu le mail précédent.',catchphrase:'« C’est clair, c’est utile… et le titre tient sur une ligne. »',certificateText:'Pour sa créativité, sa clarté et son talent à faire circuler les bonnes informations.'},
 {id:'reserve-naturelle',name:'Réserve naturelle',shortName:'Réserve naturelle',profile:{vivant:5,analyse:4,terrain:3,cadre:2},description:'Tu sais observer avant d’intervenir et comprendre les rythmes d’un espace remarquable. Entre science, vigilance et partage, tu aides à préserver un patrimoine naturel vivant.',catchphrase:'« On peut regarder longtemps : la nature finit toujours par nous apprendre quelque chose. »',certificateText:'En reconnaissance de son observation patiente, de sa rigueur et de son engagement pour la biodiversité.'}
];
